[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip STM32L031G6 --connect-under-reset --protocol swd --speed 1000"

[build]
target = "thumbv6m-none-eabi"

[env]
DEFMT_LOG = "trace"
